#!/bin/sh

# Função para verificar se um contêiner Docker está em execução
is_container_running() {
  docker ps -q -f name=kafka-ticket-sales-app
}

# Verifica se o contêiner de teste já está em execução
if [ -n "$(is_container_running)" ]; then
  echo "The test container is already running."
else
  echo "Starting the test container..."
  docker compose up -d app
fi

# Executa os testes unitários no contêiner
docker compose exec -it -T app ./mvnw test

# Captura o código de saída do comando de teste
TEST_RESULT=$?

# Verifica se os testes falharam e aborta o commit, se necessário
if [ $TEST_RESULT -ne 0 ]; then
  echo "Unit tests failed. Aborting the commit."
  exit 1
fi

# Se os testes passarem, permite o commit
exit 0
