#!/bin/sh

# Função para verificar se um contêiner Docker está em execução
is_container_running() {
  docker ps -q -f name=kafka-ticket-sales
}

# Função para verificar se uma imagem Docker existe
has_image() {
  docker image inspect kafka-ticket-sales > /dev/null 2>&1
}

if ! image_exists; then
  echo "The image was not found"
  docker build -t kafka-ticket-sales .
fi

# Verifica se o contêiner de teste já está em execução
if [ -n "$(is_container_running)" ]; then
  echo "The test container is already running. Aborting the commit."
  exit 1
fi

# Executa os testes unitários no contêiner
docker run --rm --name springboot-test kafka-ticket-sales ./mvnw test

# Captura o código de saída do comando de teste
TEST_RESULT=$?

# Finaliza e remove o contêiner de teste
docker stop kafka-ticket-sales > /dev/null
docker rm kafka-ticket-sales > /dev/null

# Verifica se os testes falharam e aborta o commit, se necessário
if [ $TEST_RESULT -ne 0 ]; then
  echo "Unit tests failed. Aborting the commit."
  exit 1
fi

# Se os testes passarem, permite o commit
exit 0
