name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t kafka-ticket-sales .
    - name: Start Docker Compose and Run Unit Test
      run: docker run -it --rm --name springboot-test kafka-ticket-sales ./mvnw test
